[[constraint]]
    name="github.com/rs/zerolog"
    version="v1.8.0"

[[constraint]]
   name="github.com/onsi/ginkgo"
   version="v1.6.0"

[[constraint]]
    name="github.com/onsi/gomega"
    version="v1.4.2"

[[override]]
   source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
   name = "gopkg.in/fsnotify.v1"

[[constraint]]
    name="github.com/nalej/derrors"
    version="=v2.0.0"

#[[constraint]]
#    name = "github.com/apache/pulsar"
#    version="=v2.3.1"

[[constraint]]
    name="github.com/Comcast/pulsar-client-go"
    version="=v0.1.1"

[[constraint]]
    name="github.com/nalej/grpc-bus-go"
    version="=v0.0.20"

[[constraint]]
    name="github.com/nalej/grpc-conductor-go"
    version="=v0.0.92"

[[constraint]]
    name="github.com/nalej/grpc-network-go"
    version="=v0.0.45"

[[constraint]]
    name="github.com/nalej/grpc-inventory-go"
    version="=v0.0.30"

[[constraint]]
    name="github.com/nalej/grpc-inventory-manager-go"
    version="=v0.0.56"

[[constraint]]
    name="github.com/nalej/grpc-application-network-go"
    version="=v0.0.11"

[[constraint]]
    name="github.com/nalej/grpc-connectivity-manager-go"
    version="=v0.0.2"


